#!/bin/bash
# /usr/bin/blurlock

# take screenshot
import -window root /tmp/screenshot.png

# blur it
#convert /tmp/screenshot.png -blur 0x7.5 /tmp/screenshotblur.png
convert /tmp/screenshot.png -scale 10% -scale 1000% /tmp/screenshotblur.png
rm /tmp/screenshot.png


B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#0377a8cc'  # default
T='#ee00eeee'  # text
W='#880000bb'  # wrong
V='#bb00bbbb'  # verifying

# lock the screen
i3lock -i /tmp/screenshotblur.png \
--insidevercolor=$C   \
--ringvercolor=$V     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T        \
--wrongcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$W       \
--bshlcolor=$W        \
\
--screen 1            \
--blur 2              \
--clock               \
--radius 110 \
--indicator           \
--timestr="%H:%M"  \
--datestr="%d/%m/%Y" \


# sleep 1 adds a small delay to prevent possible race conditions with suspend
#sleep .2

exit 0
