#!/bin/bash

ln -s ~/Dotfiles/tealdeer.toml ~/.config/tealdeer/config.toml

ln -s ~/Dotfiles/vimrc ~/.config/nvim/init.vim

ln -sf ~/Dotfiles/tmux.conf ~/.tmux.conf
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

ln -sf ~/Dotfiles/gitconfig ~/.gitconfig

ln -sf ~/Dotfiles/htoprc ~/.config/htop/htoprc

ln -sf ~/Dotfiles/i3 ~/.i3/config

ln -sf ~/Dotfiles/alacritty.yml ~/.alacritty.yml

ln -sf ~/Dotfiles/vscode.json ~/.config/VSCodium/User/settings.json

ln -sf ~/Dotfiles/dunstrc ~/Dotfiles/dunstrc

ln -sf ~/Dotfiles/trackpadg.conf ~/.config/libinput-gestures.conf

ln -sf ~/Dotfiles/swayconfig ~/.config/sway/config

ln -sf ~/Dotfiles/mako ~/.config/mako/config

ln -sf ~/Dotfiles/settings.lua ~/.config/nvim/lua/settings.lua

ln -sf ~/Dotfiles/zshrc ~/.zshrc

ln -sf ~/Dotfiles/starship ~/config/starship.toml

ln -sf ~/Dotfiles/kanshi ~/config/kanshi/config
