# https://starship.rs/config/

add_newline = false
scan_timeout = 50
command_timeout = 100
 
[rust]
disabled = true

[golang]
disabled = true

[julia]
disabled = true

[lua]
disabled = true

[dotnet]
disabled = true

[php]
disabled = true

[nodejs]
disabled = true

[cmd_duration]
min_time = 150
format = "[$duration](bold yellow)"

[git_branch]
format = "[$symbol$branch]($style) "

[package]
disabled = true

[python]
disabled = true

[aws]
disabled = true
